# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Service\KrakenApiService:
        arguments:
            $apiKey: '%kraken_api_key%'
            $apiSecret: '%kraken_api_secret%'
            $em: '@doctrine.orm.entity_manager'
            $currService: '@app.service.currency'

    app.service.currency:
        alias: AppBundle\Service\CurrencyService
        public: true

    app.service.kraken_api:
        alias: AppBundle\Service\KrakenApiService
        public: true

    AppBundle\Twig\AppExtension:
        tags: [twig.extension]
        arguments:
            $currService: '@app.service.currency'